// Code generated by 'yaegi extract github.com/elastic/go-freelru'. DO NOT EDIT.

package libs

import (
	"github.com/elastic/go-freelru"
	"reflect"
)

func init() {
	Symbols["github.com/elastic/go-freelru/freelru"] = map[string]reflect.Value{
		// type definitions
		"Metrics": reflect.ValueOf((*freelru.Metrics)(nil)),
	}
}
