// Code generated by 'yaegi extract github.com/dustin/go-humanize'. DO NOT EDIT.

package libs

import (
	"github.com/dustin/go-humanize"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/dustin/go-humanize/humanize"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BigByte":          reflect.ValueOf(&humanize.BigByte).Elem(),
		"BigBytes":         reflect.ValueOf(humanize.BigBytes),
		"BigComma":         reflect.ValueOf(humanize.BigComma),
		"BigCommaf":        reflect.ValueOf(humanize.BigCommaf),
		"BigEByte":         reflect.ValueOf(&humanize.BigEByte).Elem(),
		"BigEiByte":        reflect.ValueOf(&humanize.BigEiByte).Elem(),
		"BigGByte":         reflect.ValueOf(&humanize.BigGByte).Elem(),
		"BigGiByte":        reflect.ValueOf(&humanize.BigGiByte).Elem(),
		"BigIBytes":        reflect.ValueOf(humanize.BigIBytes),
		"BigKByte":         reflect.ValueOf(&humanize.BigKByte).Elem(),
		"BigKiByte":        reflect.ValueOf(&humanize.BigKiByte).Elem(),
		"BigMByte":         reflect.ValueOf(&humanize.BigMByte).Elem(),
		"BigMiByte":        reflect.ValueOf(&humanize.BigMiByte).Elem(),
		"BigPByte":         reflect.ValueOf(&humanize.BigPByte).Elem(),
		"BigPiByte":        reflect.ValueOf(&humanize.BigPiByte).Elem(),
		"BigQByte":         reflect.ValueOf(&humanize.BigQByte).Elem(),
		"BigQiByte":        reflect.ValueOf(&humanize.BigQiByte).Elem(),
		"BigRByte":         reflect.ValueOf(&humanize.BigRByte).Elem(),
		"BigRiByte":        reflect.ValueOf(&humanize.BigRiByte).Elem(),
		"BigSIByte":        reflect.ValueOf(&humanize.BigSIByte).Elem(),
		"BigTByte":         reflect.ValueOf(&humanize.BigTByte).Elem(),
		"BigTiByte":        reflect.ValueOf(&humanize.BigTiByte).Elem(),
		"BigYByte":         reflect.ValueOf(&humanize.BigYByte).Elem(),
		"BigYiByte":        reflect.ValueOf(&humanize.BigYiByte).Elem(),
		"BigZByte":         reflect.ValueOf(&humanize.BigZByte).Elem(),
		"BigZiByte":        reflect.ValueOf(&humanize.BigZiByte).Elem(),
		"Byte":             reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"Bytes":            reflect.ValueOf(humanize.Bytes),
		"Comma":            reflect.ValueOf(humanize.Comma),
		"Commaf":           reflect.ValueOf(humanize.Commaf),
		"CommafWithDigits": reflect.ValueOf(humanize.CommafWithDigits),
		"ComputeSI":        reflect.ValueOf(humanize.ComputeSI),
		"CustomRelTime":    reflect.ValueOf(humanize.CustomRelTime),
		"Day":              reflect.ValueOf(humanize.Day),
		"EByte":            reflect.ValueOf(constant.MakeFromLiteral("1000000000000000000", token.INT, 0)),
		"EiByte":           reflect.ValueOf(constant.MakeFromLiteral("1152921504606846976", token.INT, 0)),
		"FormatFloat":      reflect.ValueOf(humanize.FormatFloat),
		"FormatInteger":    reflect.ValueOf(humanize.FormatInteger),
		"Ftoa":             reflect.ValueOf(humanize.Ftoa),
		"FtoaWithDigits":   reflect.ValueOf(humanize.FtoaWithDigits),
		"GByte":            reflect.ValueOf(constant.MakeFromLiteral("1000000000", token.INT, 0)),
		"GiByte":           reflect.ValueOf(constant.MakeFromLiteral("1073741824", token.INT, 0)),
		"IByte":            reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"IBytes":           reflect.ValueOf(humanize.IBytes),
		"KByte":            reflect.ValueOf(constant.MakeFromLiteral("1000", token.INT, 0)),
		"KiByte":           reflect.ValueOf(constant.MakeFromLiteral("1024", token.INT, 0)),
		"LongTime":         reflect.ValueOf(humanize.LongTime),
		"MByte":            reflect.ValueOf(constant.MakeFromLiteral("1000000", token.INT, 0)),
		"MiByte":           reflect.ValueOf(constant.MakeFromLiteral("1048576", token.INT, 0)),
		"Month":            reflect.ValueOf(humanize.Month),
		"Ordinal":          reflect.ValueOf(humanize.Ordinal),
		"PByte":            reflect.ValueOf(constant.MakeFromLiteral("1000000000000000", token.INT, 0)),
		"ParseBigBytes":    reflect.ValueOf(humanize.ParseBigBytes),
		"ParseBytes":       reflect.ValueOf(humanize.ParseBytes),
		"ParseSI":          reflect.ValueOf(humanize.ParseSI),
		"PiByte":           reflect.ValueOf(constant.MakeFromLiteral("1125899906842624", token.INT, 0)),
		"RelTime":          reflect.ValueOf(humanize.RelTime),
		"SI":               reflect.ValueOf(humanize.SI),
		"SIWithDigits":     reflect.ValueOf(humanize.SIWithDigits),
		"TByte":            reflect.ValueOf(constant.MakeFromLiteral("1000000000000", token.INT, 0)),
		"TiByte":           reflect.ValueOf(constant.MakeFromLiteral("1099511627776", token.INT, 0)),
		"Time":             reflect.ValueOf(humanize.Time),
		"Week":             reflect.ValueOf(humanize.Week),
		"Year":             reflect.ValueOf(humanize.Year),

		// type definitions
		"RelTimeMagnitude": reflect.ValueOf((*humanize.RelTimeMagnitude)(nil)),
	}
}
