// Code generated by 'yaegi extract github.com/gin-contrib/cors'. DO NOT EDIT.

package libs

import (
	"github.com/gin-contrib/cors"
	"reflect"
)

func init() {
	Symbols["github.com/gin-contrib/cors/cors"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Default":          reflect.ValueOf(cors.Default),
		"DefaultConfig":    reflect.ValueOf(cors.DefaultConfig),
		"DefaultSchemas":   reflect.ValueOf(&cors.DefaultSchemas).Elem(),
		"ExtensionSchemas": reflect.ValueOf(&cors.ExtensionSchemas).Elem(),
		"FileSchemas":      reflect.ValueOf(&cors.FileSchemas).Elem(),
		"New":              reflect.ValueOf(cors.New),
		"WebSocketSchemas": reflect.ValueOf(&cors.WebSocketSchemas).Elem(),

		// type definitions
		"Config": reflect.ValueOf((*cors.Config)(nil)),
	}
}
