// Code generated by 'yaegi extract github.com/gin-contrib/pprof'. DO NOT EDIT.

package libs

import (
	"github.com/gin-contrib/pprof"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/gin-contrib/pprof/pprof"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultPrefix": reflect.ValueOf(constant.MakeFromLiteral("\"/debug/pprof\"", token.STRING, 0)),
		"Register":      reflect.ValueOf(pprof.Register),
		"RouteRegister": reflect.ValueOf(pprof.RouteRegister),
	}
}
