// Code generated by 'yaegi extract github.com/yargevad/filepathx'. DO NOT EDIT.

package libs

import (
	"github.com/yargevad/filepathx"
	"reflect"
)

func init() {
	Symbols["github.com/yargevad/filepathx/filepathx"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Glob": reflect.ValueOf(filepathx.Glob),

		// type definitions
		"Globs": reflect.ValueOf((*filepathx.Globs)(nil)),
	}
}
