// Code generated by 'yaegi extract github.com/pelletier/go-toml/v2'. DO NOT EDIT.

package libs

import (
	"github.com/pelletier/go-toml/v2"
	"reflect"
)

func init() {
	Symbols["github.com/pelletier/go-toml/v2/toml"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Marshal":    reflect.ValueOf(toml.Marshal),
		"NewDecoder": reflect.ValueOf(toml.NewDecoder),
		"NewEncoder": reflect.ValueOf(toml.NewEncoder),
		"Unmarshal":  reflect.ValueOf(toml.Unmarshal),

		// type definitions
		"DecodeError":        reflect.ValueOf((*toml.DecodeError)(nil)),
		"Decoder":            reflect.ValueOf((*toml.Decoder)(nil)),
		"Encoder":            reflect.ValueOf((*toml.Encoder)(nil)),
		"Key":                reflect.ValueOf((*toml.Key)(nil)),
		"LocalDate":          reflect.ValueOf((*toml.LocalDate)(nil)),
		"LocalDateTime":      reflect.ValueOf((*toml.LocalDateTime)(nil)),
		"LocalTime":          reflect.ValueOf((*toml.LocalTime)(nil)),
		"StrictMissingError": reflect.ValueOf((*toml.StrictMissingError)(nil)),
	}
}
