// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "AutoExecFlow",
            "url": "https://github.com/xmapst/AutoExecFlow/issues"
        },
        "license": {
            "name": "GPL-3.0",
            "url": "https://github.com/xmapst/AutoExecFlow/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/event": {
            "get": {
                "description": "订阅系统事件, SSE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "事件"
                ],
                "summary": "事件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/pool": {
            "get": {
                "description": "获取工作池信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作池"
                ],
                "summary": "详情",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SPool"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "post": {
                "description": "设置工作池大小",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作池"
                ],
                "summary": "设置",
                "parameters": [
                    {
                        "description": "pool setting",
                        "name": "setting",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SPool"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SPool"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/project": {
            "get": {
                "description": "获取项目列表, 支持WS长连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "分页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_STaskListDetailRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "post": {
                "description": "创建项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "创建",
                "parameters": [
                    {
                        "description": "项目内容",
                        "name": "content",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SProjectCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/project/{project}": {
            "get": {
                "description": "获取项目详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "project",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SProjectRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "post": {
                "description": "更新项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "content",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.SProjectUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "project",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/project/{project}/build": {
            "get": {
                "description": "获取构建列表, 支持WS长连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Build"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "project",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "分页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_STaskListDetailRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/pty": {
            "get": {
                "description": "Websocket的pty终端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "终端",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/task": {
            "get": {
                "description": "获取任务列表, 支持WS长连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "分页大小",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_STaskListDetailRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "post": {
                "description": "创建任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "创建",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "是否异步执行",
                        "name": "async",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "执行超时时间",
                        "name": "timeout",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "任务环境变量",
                        "name": "env",
                        "in": "query"
                    },
                    {
                        "description": "步骤内容",
                        "name": "steps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.SStepReq"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_STaskCreateRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/task/{task}": {
            "get": {
                "description": "获取指定任务的步骤列表, 支持WS长连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "步骤"
                ],
                "summary": "列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SStepsRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "put": {
                "description": "管理任务, 支持暂停、恢复、终止、超时暂停自动恢复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "管理",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "paused",
                            "kill",
                            "pause",
                            "resume"
                        ],
                        "type": "string",
                        "default": "paused",
                        "description": "操作项",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "1m",
                        "description": "暂停多久, 如果没设置则需要手工恢复",
                        "name": "duration",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/task/{task}/step/{step}": {
            "get": {
                "description": "指定任务指定步骤的执行输出, 支持WS长连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "步骤"
                ],
                "summary": "日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "步骤名称",
                        "name": "step",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SLogsRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "put": {
                "description": "管理指定任务的指定步骤, 支持暂停、恢复、终止、超时暂停自动恢复",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "步骤"
                ],
                "summary": "管理",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "步骤名称",
                        "name": "step",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "paused",
                            "kill",
                            "pause",
                            "resume"
                        ],
                        "type": "string",
                        "default": "paused",
                        "description": "操作项",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "1m",
                        "description": "暂停多久, 如果没设置则需要手工恢复",
                        "name": "duration",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v1/task/{task}/workspace": {
            "get": {
                "description": "获取目录列表或下载指定文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "列表或下载",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SFileListRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "post": {
                "description": "上传文件或目录",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "上传",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定目录或文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "工作目录"
                ],
                "summary": "删除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v2/task": {
            "post": {
                "description": "创建任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "创建",
                "parameters": [
                    {
                        "description": "任务内容",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.STaskReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_STaskCreateRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v2/task/{task}": {
            "get": {
                "description": "获取任务详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "任务"
                ],
                "summary": "详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_STaskRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/api/v2/task/{task}/step/{step}": {
            "get": {
                "description": "获取步骤详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "步骤"
                ],
                "summary": "详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "task",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "步骤名称",
                        "name": "step",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SStepRes"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/healthyz": {
            "get": {
                "description": "用于检测服务是否正常",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "默认"
                ],
                "summary": "健康",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SHealthyz"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        },
        "/heartbeat": {
            "get": {
                "description": "用于判断服务是否正常",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "默认"
                ],
                "summary": "心跳",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "获取版本信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "默认"
                ],
                "summary": "版本",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-types_SVersion"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.SBase-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Code": {
            "type": "integer",
            "enum": [
                0,
                1001,
                1002,
                1003,
                1004,
                1005
            ],
            "x-enum-varnames": [
                "CodeSuccess",
                "CodeRunning",
                "CodeFailed",
                "CodeNoData",
                "CodePending",
                "CodePaused"
            ]
        },
        "types.SBase-any": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SFileListRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.SFileListRes"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SHealthyz": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.SHealthyz"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SLogsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SLogRes"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SPool": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.SPool"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SProjectRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.SProjectRes"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SStepRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.SStepRes"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SStepsRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SStepRes"
                    }
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_STaskCreateRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.STaskCreateRes"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_STaskListDetailRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.STaskListDetailRes"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_STaskRes": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.STaskRes"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SBase-types_SVersion": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Code"
                        }
                    ],
                    "example": 255
                },
                "data": {
                    "$ref": "#/definitions/types.SVersion"
                },
                "msg": {
                    "type": "string",
                    "example": "message"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "types.SFileListRes": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SFileRes"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.SFileRes": {
            "type": "object",
            "properties": {
                "is_dir": {
                    "type": "boolean"
                },
                "mod_time": {
                    "type": "integer"
                },
                "mode": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "types.SHealthyz": {
            "type": "object",
            "properties": {
                "client": {
                    "type": "string"
                },
                "server": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "types.SLogRes": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "内容",
                    "type": "string"
                },
                "line": {
                    "description": "行号",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "integer"
                }
            }
        },
        "types.SPageRes": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页",
                    "type": "integer"
                },
                "size": {
                    "description": "页大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总页数",
                    "type": "integer"
                }
            }
        },
        "types.SPool": {
            "type": "object",
            "required": [
                "size"
            ],
            "properties": {
                "running": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer",
                    "example": 30
                },
                "total": {
                    "type": "integer"
                },
                "waiting": {
                    "type": "integer"
                }
            }
        },
        "types.SProjectCreateReq": {
            "type": "object",
            "required": [
                "content",
                "name",
                "type"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "disable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.SProjectRes": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "disable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.SProjectUpdateReq": {
            "type": "object",
            "required": [
                "content",
                "type"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "disable": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.SStepReq": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "步骤内容",
                    "type": "string",
                    "example": "sleep 10"
                },
                "depends": {
                    "description": "步骤依赖",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        ""
                    ]
                },
                "description": {
                    "description": "步骤描述",
                    "type": "string",
                    "example": "script.ps1"
                },
                "disable": {
                    "description": "是否禁用",
                    "type": "boolean",
                    "example": false
                },
                "env": {
                    "description": "步骤环境变量",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key": "value",
                        "key1": "value1"
                    }
                },
                "name": {
                    "description": "步骤名称",
                    "type": "string",
                    "example": "script.ps1"
                },
                "timeout": {
                    "description": "步骤超时时间",
                    "type": "string",
                    "example": "3m"
                },
                "type": {
                    "description": "步骤超时时间",
                    "type": "string",
                    "example": "powershell"
                }
            }
        },
        "types.SStepRes": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "步骤退出码",
                    "type": "integer"
                },
                "content": {
                    "description": "步骤内容",
                    "type": "string"
                },
                "depends": {
                    "description": "步骤依赖",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "步骤描述",
                    "type": "string"
                },
                "disable": {
                    "description": "是否禁用",
                    "type": "boolean"
                },
                "env": {
                    "description": "步骤环境变量",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "msg": {
                    "description": "步骤信息",
                    "type": "string"
                },
                "name": {
                    "description": "步骤名称",
                    "type": "string"
                },
                "state": {
                    "description": "步骤状态",
                    "type": "string"
                },
                "time": {
                    "description": "时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.STimeRes"
                        }
                    ]
                },
                "timeout": {
                    "description": "步骤超时时间",
                    "type": "string"
                },
                "type": {
                    "description": "步骤类型",
                    "type": "string"
                }
            }
        },
        "types.STaskCreateRes": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "步骤数量",
                    "type": "integer"
                },
                "name": {
                    "description": "任务名称",
                    "type": "string"
                }
            }
        },
        "types.STaskListDetailRes": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "分页",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.SPageRes"
                        }
                    ]
                },
                "tasks": {
                    "description": "任务列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.STaskRes"
                    }
                }
            }
        },
        "types.STaskReq": {
            "type": "object",
            "properties": {
                "async": {
                    "description": "是否异步执行",
                    "type": "boolean",
                    "example": false
                },
                "description": {
                    "description": "任务描述",
                    "type": "string"
                },
                "disable": {
                    "description": "是否禁用",
                    "type": "boolean",
                    "example": false
                },
                "env": {
                    "description": "任务环境变量",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "key": "value",
                        "key1": "value1"
                    }
                },
                "name": {
                    "description": "任务名称",
                    "type": "string",
                    "example": "task_name"
                },
                "node": {
                    "description": "Node 执行节点",
                    "type": "string",
                    "example": ""
                },
                "step": {
                    "description": "任务步骤",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.SStepReq"
                    }
                },
                "timeout": {
                    "description": "任务超时时间",
                    "type": "string",
                    "example": "24h"
                }
            }
        },
        "types.STaskRes": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "步骤数量",
                    "type": "integer"
                },
                "description": {
                    "description": "任务描述",
                    "type": "string"
                },
                "disable": {
                    "description": "是否禁用",
                    "type": "boolean"
                },
                "env": {
                    "description": "任务环境变量",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "msg": {
                    "description": "任务信息",
                    "type": "string"
                },
                "name": {
                    "description": "任务名称",
                    "type": "string"
                },
                "node": {
                    "description": "节点名称",
                    "type": "string"
                },
                "state": {
                    "description": "任务状态",
                    "type": "string"
                },
                "time": {
                    "description": "时间",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.STimeRes"
                        }
                    ]
                },
                "timeout": {
                    "description": "任务超时时间",
                    "type": "string"
                }
            }
        },
        "types.STimeRes": {
            "type": "object",
            "properties": {
                "end": {
                    "description": "结束时间",
                    "type": "string"
                },
                "start": {
                    "description": "开始时间",
                    "type": "string"
                }
            }
        },
        "types.SVersion": {
            "type": "object",
            "properties": {
                "build_time": {
                    "type": "string"
                },
                "git": {
                    "$ref": "#/definitions/types.SVersionGit"
                },
                "go": {
                    "$ref": "#/definitions/types.SVersionGO"
                },
                "user": {
                    "$ref": "#/definitions/types.SVersionUser"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "types.SVersionGO": {
            "type": "object",
            "properties": {
                "arch": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "types.SVersionGit": {
            "type": "object",
            "properties": {
                "branch": {
                    "type": "string"
                },
                "commit": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "types.SVersionUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Auto Exec Flow",
	Description:      "An `API` for cross-platform custom orchestration of execution steps\nwithout any third-party dependencies. Based on `DAG`, it implements the scheduling\nfunction of sequential execution of dependent steps and concurrent execution of\nnon-dependent steps. <br /><br /> It provides `API` remote operation mode, batch\nexecution of `Shell` , `Powershell` , `Python` and other commands, and easily\ncompletes common management tasks such as running automated operation and maintenance\nscripts, polling processes, installing or uninstalling software, updating applications,\nand installing patches.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
